services:
  s3-storage-node:
    devices:
      - /dev/fuse:/dev/fuse
    secrets:
      - cifs_credentials
      - s3_access_key
      - s3_secret_key
      - ssh_identity
      - ssh_known_hosts

secrets:
  ssh_identity:
    file: ./secrets/ssh-identity
  ssh_known_hosts:
    file: ./secrets/ssh-known-hosts
