from __future__ import annotations

from pathlib import Path

import pytest

from s3_storage_node.generation import GenerationError, render_worker_resolv_conf, resolver_nameservers


def test_resolver_nameservers_are_validated_and_deduplicated(tmp_path: Path) -> None:
    source = tmp_path / "resolv.conf"
    source.write_text(
        "nameserver 127.0.0.11\nnameserver 1.1.1.1\nnameserver 127.0.0.11\noptions ndots:0\n",
        encoding="utf-8",
    )
    assert resolver_nameservers(source) == ("127.0.0.11", "1.1.1.1")


def test_resolver_configuration_without_nameserver_fails_closed(tmp_path: Path) -> None:
    source = tmp_path / "resolv.conf"
    source.write_text("search example.test\n", encoding="utf-8")
    with pytest.raises(GenerationError, match="contains no nameserver"):
        resolver_nameservers(source)


def test_worker_resolv_conf_replaces_loopback_resolver_and_preserves_policy(tmp_path: Path) -> None:
    source = tmp_path / "source.conf"
    destination = tmp_path / "worker.conf"
    source.write_text(
        "# generated by Docker\nnameserver 127.0.0.11\nsearch service.test\noptions ndots:0 timeout:2\n",
        encoding="utf-8",
    )
    render_worker_resolv_conf(source, destination, "169.254.254.1")
    assert destination.read_text(encoding="utf-8") == (
        "nameserver 169.254.254.1\n"
        "search service.test\n"
        "options ndots:0 timeout:2\n"
    )
    assert destination.stat().st_mode & 0o777 == 0o644
